# Generated by Django 5.0.6 on 2024-09-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
